/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardWorkshopsRouteImport } from './routes/_authenticated/dashboard/workshops'
import { Route as AuthenticatedDashboardVehiclesRouteImport } from './routes/_authenticated/dashboard/vehicles'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardPurchasesRouteImport } from './routes/_authenticated/dashboard/purchases'
import { Route as AuthenticatedDashboardMyWorkshopsRouteImport } from './routes/_authenticated/dashboard/my-workshops'
import { Route as AuthenticatedDashboardMarketplaceRouteImport } from './routes/_authenticated/dashboard/marketplace'
import { Route as AuthenticatedDashboardCheckoutRouteImport } from './routes/_authenticated/dashboard/checkout'
import { Route as AuthenticatedDashboardCartRouteImport } from './routes/_authenticated/dashboard/cart'
import { Route as AuthenticatedDashboardPurchasesPurchaseIdRouteImport } from './routes/_authenticated/dashboard/purchases.$purchaseId'
import { Route as AuthenticatedDashboardPartsIdRouteImport } from './routes/_authenticated/dashboard/parts.$id'
import { Route as AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRouteImport } from './routes/_authenticated/dashboard/my-workshops.$workshopId.sales'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardWorkshopsRoute =
  AuthenticatedDashboardWorkshopsRouteImport.update({
    id: '/workshops',
    path: '/workshops',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVehiclesRoute =
  AuthenticatedDashboardVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPurchasesRoute =
  AuthenticatedDashboardPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyWorkshopsRoute =
  AuthenticatedDashboardMyWorkshopsRouteImport.update({
    id: '/my-workshops',
    path: '/my-workshops',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarketplaceRoute =
  AuthenticatedDashboardMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCheckoutRoute =
  AuthenticatedDashboardCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCartRoute =
  AuthenticatedDashboardCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPurchasesPurchaseIdRoute =
  AuthenticatedDashboardPurchasesPurchaseIdRouteImport.update({
    id: '/$purchaseId',
    path: '/$purchaseId',
    getParentRoute: () => AuthenticatedDashboardPurchasesRoute,
  } as any)
const AuthenticatedDashboardPartsIdRoute =
  AuthenticatedDashboardPartsIdRouteImport.update({
    id: '/parts/$id',
    path: '/parts/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute =
  AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRouteImport.update({
    id: '/$workshopId/sales',
    path: '/$workshopId/sales',
    getParentRoute: () => AuthenticatedDashboardMyWorkshopsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/cart': typeof AuthenticatedDashboardCartRoute
  '/dashboard/checkout': typeof AuthenticatedDashboardCheckoutRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/my-workshops': typeof AuthenticatedDashboardMyWorkshopsRouteWithChildren
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/vehicles': typeof AuthenticatedDashboardVehiclesRoute
  '/dashboard/workshops': typeof AuthenticatedDashboardWorkshopsRoute
  '/dashboard/parts/$id': typeof AuthenticatedDashboardPartsIdRoute
  '/dashboard/purchases/$purchaseId': typeof AuthenticatedDashboardPurchasesPurchaseIdRoute
  '/dashboard/my-workshops/$workshopId/sales': typeof AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/cart': typeof AuthenticatedDashboardCartRoute
  '/dashboard/checkout': typeof AuthenticatedDashboardCheckoutRoute
  '/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/dashboard/my-workshops': typeof AuthenticatedDashboardMyWorkshopsRouteWithChildren
  '/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRouteWithChildren
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/vehicles': typeof AuthenticatedDashboardVehiclesRoute
  '/dashboard/workshops': typeof AuthenticatedDashboardWorkshopsRoute
  '/dashboard/parts/$id': typeof AuthenticatedDashboardPartsIdRoute
  '/dashboard/purchases/$purchaseId': typeof AuthenticatedDashboardPurchasesPurchaseIdRoute
  '/dashboard/my-workshops/$workshopId/sales': typeof AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/cart': typeof AuthenticatedDashboardCartRoute
  '/_authenticated/dashboard/checkout': typeof AuthenticatedDashboardCheckoutRoute
  '/_authenticated/dashboard/marketplace': typeof AuthenticatedDashboardMarketplaceRoute
  '/_authenticated/dashboard/my-workshops': typeof AuthenticatedDashboardMyWorkshopsRouteWithChildren
  '/_authenticated/dashboard/purchases': typeof AuthenticatedDashboardPurchasesRouteWithChildren
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/vehicles': typeof AuthenticatedDashboardVehiclesRoute
  '/_authenticated/dashboard/workshops': typeof AuthenticatedDashboardWorkshopsRoute
  '/_authenticated/dashboard/parts/$id': typeof AuthenticatedDashboardPartsIdRoute
  '/_authenticated/dashboard/purchases/$purchaseId': typeof AuthenticatedDashboardPurchasesPurchaseIdRoute
  '/_authenticated/dashboard/my-workshops/$workshopId/sales': typeof AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/cart'
    | '/dashboard/checkout'
    | '/dashboard/marketplace'
    | '/dashboard/my-workshops'
    | '/dashboard/purchases'
    | '/dashboard/settings'
    | '/dashboard/vehicles'
    | '/dashboard/workshops'
    | '/dashboard/parts/$id'
    | '/dashboard/purchases/$purchaseId'
    | '/dashboard/my-workshops/$workshopId/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/cart'
    | '/dashboard/checkout'
    | '/dashboard/marketplace'
    | '/dashboard/my-workshops'
    | '/dashboard/purchases'
    | '/dashboard/settings'
    | '/dashboard/vehicles'
    | '/dashboard/workshops'
    | '/dashboard/parts/$id'
    | '/dashboard/purchases/$purchaseId'
    | '/dashboard/my-workshops/$workshopId/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/cart'
    | '/_authenticated/dashboard/checkout'
    | '/_authenticated/dashboard/marketplace'
    | '/_authenticated/dashboard/my-workshops'
    | '/_authenticated/dashboard/purchases'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/vehicles'
    | '/_authenticated/dashboard/workshops'
    | '/_authenticated/dashboard/parts/$id'
    | '/_authenticated/dashboard/purchases/$purchaseId'
    | '/_authenticated/dashboard/my-workshops/$workshopId/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/workshops': {
      id: '/_authenticated/dashboard/workshops'
      path: '/workshops'
      fullPath: '/dashboard/workshops'
      preLoaderRoute: typeof AuthenticatedDashboardWorkshopsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/vehicles': {
      id: '/_authenticated/dashboard/vehicles'
      path: '/vehicles'
      fullPath: '/dashboard/vehicles'
      preLoaderRoute: typeof AuthenticatedDashboardVehiclesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/purchases': {
      id: '/_authenticated/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof AuthenticatedDashboardPurchasesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-workshops': {
      id: '/_authenticated/dashboard/my-workshops'
      path: '/my-workshops'
      fullPath: '/dashboard/my-workshops'
      preLoaderRoute: typeof AuthenticatedDashboardMyWorkshopsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/marketplace': {
      id: '/_authenticated/dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/dashboard/marketplace'
      preLoaderRoute: typeof AuthenticatedDashboardMarketplaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/checkout': {
      id: '/_authenticated/dashboard/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AuthenticatedDashboardCheckoutRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/cart': {
      id: '/_authenticated/dashboard/cart'
      path: '/cart'
      fullPath: '/dashboard/cart'
      preLoaderRoute: typeof AuthenticatedDashboardCartRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/purchases/$purchaseId': {
      id: '/_authenticated/dashboard/purchases/$purchaseId'
      path: '/$purchaseId'
      fullPath: '/dashboard/purchases/$purchaseId'
      preLoaderRoute: typeof AuthenticatedDashboardPurchasesPurchaseIdRouteImport
      parentRoute: typeof AuthenticatedDashboardPurchasesRoute
    }
    '/_authenticated/dashboard/parts/$id': {
      id: '/_authenticated/dashboard/parts/$id'
      path: '/parts/$id'
      fullPath: '/dashboard/parts/$id'
      preLoaderRoute: typeof AuthenticatedDashboardPartsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-workshops/$workshopId/sales': {
      id: '/_authenticated/dashboard/my-workshops/$workshopId/sales'
      path: '/$workshopId/sales'
      fullPath: '/dashboard/my-workshops/$workshopId/sales'
      preLoaderRoute: typeof AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRouteImport
      parentRoute: typeof AuthenticatedDashboardMyWorkshopsRoute
    }
  }
}

interface AuthenticatedDashboardMyWorkshopsRouteChildren {
  AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute: typeof AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute
}

const AuthenticatedDashboardMyWorkshopsRouteChildren: AuthenticatedDashboardMyWorkshopsRouteChildren =
  {
    AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute:
      AuthenticatedDashboardMyWorkshopsWorkshopIdSalesRoute,
  }

const AuthenticatedDashboardMyWorkshopsRouteWithChildren =
  AuthenticatedDashboardMyWorkshopsRoute._addFileChildren(
    AuthenticatedDashboardMyWorkshopsRouteChildren,
  )

interface AuthenticatedDashboardPurchasesRouteChildren {
  AuthenticatedDashboardPurchasesPurchaseIdRoute: typeof AuthenticatedDashboardPurchasesPurchaseIdRoute
}

const AuthenticatedDashboardPurchasesRouteChildren: AuthenticatedDashboardPurchasesRouteChildren =
  {
    AuthenticatedDashboardPurchasesPurchaseIdRoute:
      AuthenticatedDashboardPurchasesPurchaseIdRoute,
  }

const AuthenticatedDashboardPurchasesRouteWithChildren =
  AuthenticatedDashboardPurchasesRoute._addFileChildren(
    AuthenticatedDashboardPurchasesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCartRoute: typeof AuthenticatedDashboardCartRoute
  AuthenticatedDashboardCheckoutRoute: typeof AuthenticatedDashboardCheckoutRoute
  AuthenticatedDashboardMarketplaceRoute: typeof AuthenticatedDashboardMarketplaceRoute
  AuthenticatedDashboardMyWorkshopsRoute: typeof AuthenticatedDashboardMyWorkshopsRouteWithChildren
  AuthenticatedDashboardPurchasesRoute: typeof AuthenticatedDashboardPurchasesRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardVehiclesRoute: typeof AuthenticatedDashboardVehiclesRoute
  AuthenticatedDashboardWorkshopsRoute: typeof AuthenticatedDashboardWorkshopsRoute
  AuthenticatedDashboardPartsIdRoute: typeof AuthenticatedDashboardPartsIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCartRoute: AuthenticatedDashboardCartRoute,
    AuthenticatedDashboardCheckoutRoute: AuthenticatedDashboardCheckoutRoute,
    AuthenticatedDashboardMarketplaceRoute:
      AuthenticatedDashboardMarketplaceRoute,
    AuthenticatedDashboardMyWorkshopsRoute:
      AuthenticatedDashboardMyWorkshopsRouteWithChildren,
    AuthenticatedDashboardPurchasesRoute:
      AuthenticatedDashboardPurchasesRouteWithChildren,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardVehiclesRoute: AuthenticatedDashboardVehiclesRoute,
    AuthenticatedDashboardWorkshopsRoute: AuthenticatedDashboardWorkshopsRoute,
    AuthenticatedDashboardPartsIdRoute: AuthenticatedDashboardPartsIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
